import { EditorThemeClasses } from "lexical";

const NoteEditorTheme: EditorThemeClasses = {
    ltr: "ltr",
    rtl: "rtl",
    paragraph: "leading-normal",
    quote: "text-muted-foreground border-l-[2px] bg-muted/50 border-l-border pl-4 py-0.5 my-1",
    heading: {
        h1: "text-4xl font-semibold leading-tight mb-2",
        h2: "text-3xl font-semibold leading-tight mb-2",
        h3: "text-2xl font-semibold leading-normal mb-1",
        h4: "text-xl font-semibold leading-relaxed mb-1",
        h5: "text-lg font-semibold leading-relaxed mb-1",
        h6: "text-lg font-medium leading-relaxed mb-1",
    },
    hashtag: "text-muted-foreground border-b border-b-border",
    text: {
        bold: "font-semibold",
        italic: "italic",
        strikethrough: "line-through",
        underline: "underline",
    },
    list: {
        ul: "list-disc list-outside py-1 pl-6",
        ol: "list-decimal list-outside py-1 pl-6",
    },
    link: "text-muted-foreground underline",
    code: "bg-muted w-full block p-2 rounded border-border border text-sm",
    codeHighlight: {
        atrule: "text-[hsl(350,40%,70%)]",
        attr: "text-[hsl(350,40%,70%)]",
        attrname: "testing",
        boolean: "text-[#FAE3C6]",
        builtin: "text-[#fab0cb]",
        cdata: "text-muted-foreground",
        char: "text-[hsl(350,40%,70%)]",
        class: "text-[#dafbac]",
        "class-name": "text-[#dafbac]",
        comment: "text-muted-foreground",
        constant: "text-[#d193e4]",
        deleted: "text-[#FAE3C6]",
        doctype: "text-muted-foreground",
        entity: "text-[#fab0cb]",
        function: "text-[#dafbac]",
        important: "text-[#e90]",
        inserted: "text-[hsl(350,40%,70%)]",
        keyword: "text-[#d193e4]",
        namespace: "text-muted-foreground",
        number: "text-[#FAE3C6]",
        operator: "text-muted-foreground",
        prolog: "text-muted-foreground",
        property: "text-[#FAE3C6]",
        punctuation: "text-muted-foreground",
        regex: "text-[#e90]",
        selector: "text-[hsl(350,40%,70%)]",
        string: "text-[#fab0cb]",
        symbol: "text-[#FAE3C6]",
        tag: "text-[#FAE3C6]",
        url: "text-[#fab0cb]",
        variable: "text-[#fab0cb]",
    },
};

export default NoteEditorTheme;
